README.md, package-lock.json, package.json
* Use https://codecov.io for test coverage reporting
* Remove support for coveralls
=> use codecov for test coverage reporting

package.json, src/version.js, test/version.test.js
* Remove beta tag from version
* Add test to ensure bundled version matches `package.json`
=> remove beta

package.json, src/api/geocoding.js, src/index.js, src/version.js, test/index.test.js
https://app.clubhouse.io/radarlabs/story/2166/web-sdk-support-custom-ip-address
=> Support custom IP

package.json, src/api/track.js, src/cookie.js, src/index.js, src/version.js, test/api/track.test.js, test/index.test.js
https://app.clubhouse.io/radarlabs/story/2241/add-setmetadata-to-js-sdk
=> Expose setMetadata

package-lock.json, package.json, src/version.js, test/api/search.test.js, test/version.test.js
https://app.clubhouse.io/radarlabs/story/3346/web-sdk-fix-autocomplete-tests-bump-version
=> Fix autocomplete tests, bump version

package-lock.json
=> CVE serialize-javascript 2.1.2

demo/test.html, package.json, src/index.js, src/version.js, test/api/routing.test.js
Fix to the getMatrix method to ensure the correct top level response objects are returned. 
cc @kochis @corypisano @jsani-radar
=> Matrix hotfix

demo/test.html, package.json, src/index.js, src/version.js, test/api/routing.test.js
Reverts radarlabs/radar-sdk-js#56
=> Revert "Matrix hotfix"

demo/test.html, package.json, src/index.js, src/version.js, test/api/routing.test.js
=> Hotfix for matrix api

demo/test.html, src/api/trips.js, test/api/track.test.js, test/api/trips.test.js
Adding support for `tripOptions.approachingThreshold`.
=> Add approachingThreshold to trip options

package-lock.json, package.json, src/api/track.js, src/api/trips.js, src/index.js, src/version.js, test/api/track.test.js, test/api/trips.test.js
- Reverting PR https://github.com/radarlabs/radar-sdk-js/commit/3f6edde917ddd52b872c7bfe1002c0cd51b50fed that had the trips changes before rolling out anywhere
```bash
curl 'https://api.radar.io/v1/track' \
-H 'authority: api.radar.io' \
-H 'accept: */*' \
-H 'accept-language: en-US,en;q=0.9' \
-H 'authorization: prj_test_pk_... \
-H 'content-type: application/json' \
-H 'origin: http://localhost:8080' \
-H 'referer: http://localhost:8080/' \
-H 'sec-ch-ua: "Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"' \
-H 'sec-ch-ua-mobile: ?0' \
-H 'sec-ch-ua-platform: "macOS"' \
-H 'sec-fetch-dest: empty' \
-H 'sec-fetch-mode: cors' \
-H 'sec-fetch-site: cross-site' \
-H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) …
```
=> Revert trips changes

demo/test.html, src/api/events.js, src/index.js, test/api/events.test.js
=> custom events api

src/api/routing.js
=> add geometry points

MIGRATION.md, README.md
Fixes: https://github.com/radarlabs/radar-sdk-js/issues/111
=> fix references to maplibre-gl package in docs

README.md, demo/views/display-a-map.hbs, package-lock.json, package.json, src/ui/map.ts, src/version.ts
=> Add support for new radar styles

CONTRIBUTING.md, README.md, package-lock.json, package.json, src/types.ts, src/ui/autocomplete.ts, src/ui/map.ts, src/version.ts, styles/radar.css
* Expose more options for markers
* Support `maxHeight` for autocomplete results
https://github.com/radarlabs/radar-sdk-js/assets/814934/62bdb1c8-d07c-48dd-bfff-460d27768eff
=> New map and autocomplete options

src/types.ts, src/ui/autocomplete.ts
* Add support for `expandUnits` param to autocomplete input
=> Add support for expandUnits to autocomplete input

src/types.ts, src/ui/RadarMarker.ts
```
const marker = Radar.ui.marker({ 
popup: { text: 'My popup!', maxWidth: '300px', className: 'custom-popup' }
});
```
=> RadarMarker popup improvements

package.json
v4 release notes: https://github.com/maplibre/maplibre-gl-js/releases/tag/v4.0.0]
tldr no relevant breaking changes
=> Bump maplibre version

README.md, package-lock.json, package.json, src/ui/RadarMarker.ts, src/version.ts
* Use marker id instead of url
=> Fix bug using wrong cache key for custom markers

README.md, package-lock.json, package.json, src/api.ts, src/logger.ts, src/ui/RadarMap.ts, src/ui/autocomplete.ts, src/version.ts
* Fix bug when logging mapOptions in debug mode when using a react `ref` as the container
=> Fix react ref bug in debug mode

README.md, package-lock.json, package.json, src/api.ts, src/api/track.ts, src/api/verify.ts, src/http.ts, src/ui/RadarMap.ts, src/version.ts, test/http.test.ts
Android equivalent: https://github.com/radarlabs/radar-sdk-android/pull/426
iOS equivalent: https://github.com/radarlabs/radar-sdk-ios/pull/427
=> avoid double request, add clearVerifiedLocationToken()

styles/radar.css
- Adds a sans-serif font fallback
=> Autocomplete fallback font-family
