- package.json
- src/index.js
- src/version.js
- test/index.test.js
Expose `STATUS` codes on `Radar` class.
> expose STATUS codes

- README.md
- demo/test.html
- src/http.js
- src/index.js
- test/http.test.js
- test/index.test.js
Made a few adjustments to make the success/error cases more consistent:
> response available on error

- demo/test.html
- package.json
- src/version.js
Since this doesn't have support for node, we don't need the `module` property set (should just use the `main` property).
> remove module from package. make demo page IE 11 friendly

- .github/workflows/codeql-analysis.yml
- package-lock.json
- this revert fixes the uglify error. This will however bring back the gh dependency security alert.
- adding CodeQL for code scanning.
- https://trello.com/c/3GpWnbnn/782-set-up-gh-code-scanning
> reverting serialize-javascript and add CodeQL

- package-lock.json
- package.json
- src/api/geocoding.js
- src/api/search.js
- src/version.js
- test/api/search.test.js
Adds support for `country` filter on geocode & autocomplete endpoint.
Docs: https://radar.com/documentation/api#query-parameters-1
> Add support for country param in geocode endpoints

- .circleci/config.yml
Uses new CircleCI convenience images: https://circleci.com/developer/images?imageType=docker.
Bumps the node version (patch number only) to get a more recent image (April 2022).
> Move to new convenience image for CircleCI. Bump revision.

- package-lock.json
- package.json
- src/api/context.js
- src/api/geocoding.js
- src/api/routing.js
- src/api/search.js
- src/api/track.js
- src/api/trips.js
- src/http.js
- src/version.js
- test/api/search.test.js
- test/api/trips.test.js
- test/http.test.js
Story details: https://app.shortcut.com/radarlabs/story/12086
All tests pass
```
Context
getContext
location permissions denied
✓ should throw a navigation error
location permissions approved
✓ should return a context response
Geocoding
geocode
✓ should return an address
reverseGeocode
location permissions denied
✓ should propagate the navigator error
location permissions approved
✓ should return a geocode response
ipGeocode
✓ should return a geocode response
Routing
getDistanceToDestination
location permissions denied
✓ should throw a navigation error
location permissions approved
no args given
✓ should return a routing response
all args given
✓ should return a routing response
getMatrixDistances
location permissions denied
✓ should throw a navigation error
location permissions approved …
```
> Use BASE_API_PATH for all endpoints in JS SDK

- package-lock.json
- package.json
- src/api_host.js
- src/http.js
- src/index.js
- src/storage.js
- src/version.js
When setting items in session storage, `null` and `undefined` values were being set as strings `"null"`, `"undefined"`. 
According to the existing logic in `Storage.getItem`, these values weren't intended to be stored in the first place. This check in `Storage.getItem` is never hit since every value pulled from storage are strings.
https://github.com/radarlabs/radar-sdk-js/blob/2cc470776b8989bf5ae02e711056ecce7ec1f229/src/storage.js#L53-L64
This caused an error in every API request made in #75. Calling `Radar.setHost(apiHost)` would set the url to be `apiHost/undefined/...` when it should've defaulted to `apiHost/v1/...`
> Hotfix null and undefined check for session storage

- package-lock.json
- package.json
- src/api/track.js
- src/index.js
- src/navigator.js
- src/storage.js
- src/version.js
Difficult to write test for. Tested manually:
*Include screenshots, responses, or steps to verify the code works as expected*
Can verify locally by setting up local sdk, or verify that it works using vercel:
https://frontend-git-boon-sdk-demo-branch-radarlabs.vercel.app/demo/js
Currently cached location time is 30 seconds. So go to link in safari, enter prompt for location.
After you can continuously reload for up to 30 seconds without being re-prompted for your location, but then after 30 seconds you'll get prompted again
I probably should have just installed loom on safari but here we are:
https://youtu.be/VU5nAQ74pyo
docs:
https://github.com/radarlabs/documentation/pull/232
> RAD-5740: cache-recent-locations-in-websdk-with-variable-ttl

- package-lock.json
- package.json
- src/api/track.js
- src/api/trips.js
- src/index.js
- src/version.js
- test/api/track.test.js
- test/api/trips.test.js
- Add `startTrip` service to use new `POST` endpoint
- Update `updateTrip` to new `PATCH` endpoint
- Add `version` field to `tripOptions` on `track`
- Add `scheduledArrivalAt` to `tripOptions`
- Update tests
Fixes TRIPS-92, TRIPS-172
> Update trips behavior to new endpoints and new /track tripOptions

- demo/test.html
- package-lock.json
- package.json
- src/api/events.js
- src/index.js
- src/version.js
- test/api/events.test.js
There is no idea of a "session" for web sdk so we will not be doing `opened_app` here. Instead we are just making the header changes for `logConversion` with the additional capability of taking in a `revenue` param
Open Q: should we add a migration guide file?
QA:
* added tests that are passing in the CI
* added to the local browser test and it is working
> CORE-295 conversions to web sdk

- README.md
- package-lock.json
- package.json
- src/ui/map.ts
- src/version.ts
- styles/radar.css
Default to showing map attribution, using the non-compact style
> Add default attribution

- src/ui/autocomplete.ts
* If blur is triggered by the "powered by" link click, close the drawer asynchronously (with a small delay)
> Fix autocomplete closing before link event can propagate

- src/api/track.ts
- src/session.ts
* Truncate decimals off sessionId
* Send `locationAuthorization` in track requests
> Truncate session and send location authorization in track requests

- demo/views/create-autocomplete.hbs
- src/ui/autocomplete.ts
* Adds support for providing the `<input>` for autocomplete UI
> support providing input element for autocomplete ui

- README.md
- demo/views/layouts/main.hbs
- demo/views/track-verified-token.hbs
- package-lock.json
- package.json
- src/api/verify.ts
- src/index.ts
- src/types.ts
- src/version.ts
- exposes `Radar.trackVerifiedToken()`
- adds a new demo page
> add trackVerifiedToken()

- src/types.ts
- test/radar.test.ts
Fixes https://github.com/radarlabs/radar-sdk-js/issues/124
* `addressess` in `RadarAutocompleteResponse` should be an array of addresses.
> Ensure array of addresses is defined in RadarAutocompleteResponse

- package-lock.json
- package.json
- src/types.ts
- src/ui/autocomplete.ts
- src/version.ts
Added `hideResultsOnBlur` option so that the results list persist on click away.
Also, added `setOptions` function so that the autocomplete element does not have to be completely rerendered everytime an option changes.
These are needed for internal usage
https://www.loom.com/share/2084a71a836041ebbed533a88fe7a27c
> hideResultsOnBlur and setOptions

- README.md
- scripts/bump-version.cjs
* Updates README with latest SDK version in examples
* Make the `bump-version` script more resilient to version updates (does not need to have an exact match to previous version)
> More resilient readme updates when bumping version

- README.md
- package-lock.json
- package.json
- src/api/track.ts
- src/version.ts
sends IANA time zone identifier for the browser's time zone, such as `"America/New_York"` or `"Europe/Paris"`, to `POST /track`
> send time zone to POST /track

- README.md
- package-lock.json
- package.json
- src/navigator.ts
- src/types.ts
- src/ui/RadarMap.ts
- src/version.ts
Adds the map option `language` to configure map language. This only works for Radar map styles as it searchs and replaces for the expression `["get", "radar:name_client_language"]`.
Also sends up the header `X-Radar-Device-Language` with every style request which grabs from `navigator.language`. This is so that the server can figure out how to transform the style appropriately given the browser language.
> Map initalization `language` param

- src/ui/RadarMarker.ts
Tries to keep the event payload more in line with [maplibre mouse events](https://github.com/maplibre/maplibre-gl-js/blob/350064ecfe6c4bd074a19b5e7195cf010bede168/src/ui/events.ts#L475-L532). 
Since we're extending their `Marker` class, there's gonna be limitations as towards how flexible this event + event payload can be. Mainly, it's gonna be really tricky trying to stop event propagation to the map itself since all of maplibre's event are built using the map event listener. For example, they determine which element was "clicked" by checking if the event target contains the map element AND a marker in their own marker click handler. Their popup click handler is also tied to the map click event so we ideally we are not interfering with it.
> Allow map event propagation on marker click

- README.md
- package-lock.json
- package.json
- src/ui/autocomplete.ts
- src/version.ts
The main fix is to change from `event.code` to `event.key` for handling keyboard events, which was breaking on Windows/Edge.
Other enhancements are additional aria-roles for accessibility.
> Fix autocomplete keyboard control on Windows/Edge

- src/api/search.ts
- src/http.ts
- src/ui/autocomplete.ts
- styles/radar.css
* Fixes a race-condition on autocomplete requests
* Disable browser autofill for address autocomplete
* Autocomplete style fixes
There is a subtle race condition in the autocomplete component that exists when a previous request completes before the latest request. In the scenario where multiple requests are in-flight, the first request to complete sets the results (regardless if the user has typed more characters). The fix is to cancel any in-flight requests when another is issued.
Note: responses are manually throttled down in the examples to demonstrate the issue
https://github.com/user-attachments/assets/69927fc6-688e-4e57-a02d-a80784d0c662
https://github.com/user-attachments/assets/1821f72a-ea65-4ace-8f07-7e085e857674
> Autocomplete fixes (race condition, prevent autofill, style fixes)

- src/ui/RadarMap.ts
Rely on the `Authorization` header to provide publishable key instead of query param for maps.
> Use auth header for publishable key

- demo/views/add-a-marker.hbs
- demo/views/add-a-polyline.hbs
- demo/views/add-geojson.hbs
- demo/views/display-a-map.hbs
- demo/views/layouts/main.hbs
- src/index.ts
- src/types.ts
- src/ui/RadarLineFeature.ts
- src/ui/RadarMap.ts
- src/ui/RadarMapFeature.ts
- src/ui/RadarMarker.ts
- src/ui/RadarPolygonFeature.ts
- src/ui/RadarPopup.ts
- src/ui/map.ts
- src/util/geojson.ts
- src/util/object.ts
- src/util/polyline.ts
* Add support for drawing lines and polygons
* Support for polyline rendering
* Introduces a new `RadarFeature` class for adding GeoJSON features to the map.
Usage:
```js
// adding a polyline to the map
const polyline = 'iyeulAveaclCuVfw@aA|CuAlEgj@teBm@jBs@|BbBjA~XzRdFnDfBlA`A{C`@mA~h@icBfAmD`A{Cff@c|A|A{E|BZfJrAh[lEhC^dBThMdBnTtCd@LzBx@|BjA^RhZnUzBdB`BtAl\\zWvAjAlBzA|UjRfEhD`ClBhRfOlCxBjBxAhBxAxKzItNhL|BhBnB|Af]rXnB~A|AnAn[fWbAv@~ArAzBfBxStPbInGtB`BlBzA~b@l]bAx@d@\\jBxAjMdKTPxGlFnJvH|StPnCxBhFbEr@{EfEeYvCyRf@kD\\{BBUtC}RfAoFbAcFpDsNl@_Cl@aCfLcd@r@sCn@cC`Lsc@p@kCl@aCjE}P`E}Od@iBz@{DrD`A|JxCxWdFxc@fLzIzBzL~C~Bj@dAXlg@rM~Ab@pA^|`@pLp@RtBl@bBf@xEpAjQ`FtBl@xF~AjEjAtIbCxGMzWjIhCv@jBl@ju@pUnCz@pCdAvRnIfUpJlV~KtBbAlB~@l`@|SvBhAXNjCvApLnGxBlAnFtCnGeEbZyQ~G}E`B}AhBsBfByBnFkH|AiBzAeBzAcB|A{AdB}ApBw …
```
> Add line and polygon drawing support

- README.md
- package-lock.json
- package.json
- src/ui/RadarMarker.ts
- src/version.ts
* Rather than re-created the URL object from the blob data, just re-use the same cached image each time
> Re-use url object in cache

- README.md
- package-lock.json
- package.json
- src/api/geocoding.ts
- src/api/search.ts
- src/types.ts
- src/version.ts
- adds support for the `lang` param for `autocomplete` and `forwardGeocode`
- adds `timeZone` property in response for `forwardGeocode`, `reverseGeocode`, `ipGeocode`
- adds neighborhood layer type to `RadarGeocodeLayer`
> Update params and types for geocoding and search API

- README.md
- package-lock.json
- package.json
- src/api/search.ts
- src/types.ts
- src/ui/autocomplete.ts
- src/version.ts
- also fixes `lang` param not being passed in to the autocomplete UI kit
> Add postalCode param and handle null setters

- README.md
- package-lock.json
- package.json
- src/api/verify.ts
- src/navigator.ts
- src/version.ts
- change location timeout to 10 seconds to match mobile SDKs
- catch `trackVerified()` errors in `startTrackingVerified()` to ensure tracking doesn't stop
- bump version to `4.4.8`
> Catch `trackVerified()` errors in `startTrackingVerified()`, change location timeout to 10 seconds

- package-lock.json
- package.json
Allow maplibre 5.0.1 for Globe support
> Update maplibre-gl Peer Dependency

- README.md
- package-lock.json
- package.json
- src/ui/RadarMap.ts
- src/version.ts
* Update MapLibre to v5 so distributed versions that include the SDK also include GlobeView
* Skip style validation if a live key is used
> Update MapLibre dependency to v5

- package-lock.json
- src/types.ts
Adding an optional `reason` param to track params
Use Case:
```
Radar.track({ userId: 'test-user-id', reason: 'test-reason'})
```
Including reasons in the trackOnce request:
Not including reasons:
> FRA-1076: add optional reason to track params

- src/ui/RadarMap.ts
Fix for issue mentioned here: https://github.com/maplibre/maplibre-gl-js/issues/5932
> Remove `minZoom` default
